name: Build and Package Java Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '14'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create application image
      run: |
        mkdir -p build/output
        jpackage --input build/libs --main-jar MyApp.jar --main-class com.example.MainClass --name MyApp --type app-image --dest build/output

    - name: Create Windows EXE
      run: |
        jpackage --input build/output/MyApp --name MyApp --main-class com.example.MainClass --type exe --dest build/output

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: MyApp-exe
        path: build/output/MyApp-*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download EXE artifact
      uses: actions/download-artifact@v3
      with:
        name: MyApp-exe
        path: build/output

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: build/output/MyApp-*.exe