name: Build and Package Java Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Verify Java Version
      run: java -version

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle
      run: ./gradlew.bat build

    - name: Create application image
      run: |
        mkdir -p build/output
        jpackage --input build/libs --main-jar cardanolips.jar --main-class com.example.MainClass --name cardanolips --type app-image --dest build/output

    - name: Create Windows EXE
      run: |
        jpackage --input build/output/cardanolips --name cardanolips --main-class com.example.MainClass --type exe --dest build/output

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: cardanolips-exe
        path: build/output/cardanolips-*.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download EXE artifact
      uses: actions/download-artifact@v3
      with:
        name: cardanolips-exe
        path: build/output

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: build/output/cardanolips-*.exe
